### PR TITLE
Fixing DefaultConfig constant

### LINKED ISSUE #65: DefaultConfig for nuget config file produces invalid config
https://github.com/OneGet/NuGetProvider/blob/16519ed5cbbae967a1aeaa383614bcb4505f46ab/NugetLightRequest.cs#L85-L89

Is the default config for a nuget.config if not found in this provider code.  It produces an invalid nuget.config (no sources) and can result in a machine not being able to do any restores for apps or other things relying on nuget going forward.

### PR DESCRIPTION
**Pull request by timheuer**
Fixes #65 by adding a default package source instead of none -- this is the default config that is added via nuget.exe outside of this scenario to match.

### CODE REVIEW

File: NugetLightRequest.cs [hunk 1]
```diff
@@ -85,6 +85,7 @@ public override SecureString CredentialPassword
         internal const string DefaultConfig = @"<?xml version=""1.0""?>
 <configuration>
   <packageSources>
+    <add key=""nuget.org"" value=""https://api.nuget.org/v3/index.json"" protocolVersion=""3"" />
```
Comment (SteveL-MSFT) [inline NugetLightRequest.cs:88]: Has this been verified to not have any impact on PowerShellGet v2 which relies on this provider?

Comment (timheuer) [reply NugetLightRequest.cs:88]: I was looking for some tests to validate the scenarios.  What's the easiest way to validate? There is varying docs on what is now included in PS6+ versus < 5 etc. and I'm not sure what the best way to look at the matrix is here (e.g., PS7.2 includes the provider)

Comment (timheuer) [reply NugetLightRequest.cs:88]: The build is failing on other aspects of the build script (older references) -- looks like prior builds failed as well. I can't build locally as I don't have access to some rel feeds it appears.
```
  Determining projects to restore...
C:\Users\timheuer\source\repos\NuGetProvider\NuGetProvider.csproj : error NU1301: Unable to load the service index for
source https://pkgs.dev.azure.com/powershell-rel/PackageManagement/_packaging/InternalPkgMgmtFeed/nuget/v3/index.json.
```

Comment (SteveL-MSFT) [reply NugetLightRequest.cs:88]: Honestly, OneGet isn't being maintained and effectively deprecated.  So this might be more effort that it's worth.  Maybe be better to have this issue opened as a doc bug for PackageManagement.

Comment (timheuer) [reply NugetLightRequest.cs:88]: Not knowing what the component structure is or where "OneGet" gets exposed to customers, I can't comment accurately on this, but it does feel like the default experience is broken for `Install-Package` and the like in some circumstances.  Unfortunately the resulting error messages wouldn't lead to any logical PackageManagement documentation point either.  This transient aspect results in breaking OTHER scenarios as well, namely `dotnet build` and other CLI-based operations for `dotnet`

Comment (TravisEz13) [reply NugetLightRequest.cs:88]: @alerickson We should not be using `powershell-rel` in public.  Can we discuss why this is needed and come up with an alternative?

Comment (zivkan) [reply NugetLightRequest.cs:88]: FWIW, this appears to be affecting a bunch of Azure Pipelines and GitHub Actions customers: https://github.com/actions/virtual-environments/issues/5768
